# Site settings
title: FELIZ CUMPLE MES MI VIDA
email: your-email@domain.com
url: https://example.github.io
description: "Mi vida Hermoso no puedo creer a veces que estamos juntos luegos de tantas cosas que nos han pasado pero está vez el destino está de nuestro lado. Te amo mi vida Feliz 2do Mes de muchos!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Att. André!

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/dandrevill

# Build settings
markdown: kramdown
permalink: pretty
